In [1]:
import pandas as pd
import numpy as np

In [3]:
# df = pd.read_excel("./mapping/unimelb_southbank_url.xlsx") #Southbank
df = pd.read_excel("./mapping/unimelb_dookie_url.xlsx") #Southbank

In [4]:
df['No'] = df['No'].astype(str)

In [6]:
mapping_naming = pd.read_excel("Buidling_mapping_Mazemap.xlsx")
mapping_naming

,Campus Code,Building Code,Building Name
0,PAR,101,BEAUREPAIRE CENTRE
1,PAR,102,DAVID PENINGTON BUILDING
2,PAR,103,NONA LEE SPORTS CENTRE
3,PAR,104,ALAN GILBERT BUILDING
4,PAR,105,FBE BUILDING
...,...,...,...
643,WER,EXT-W700,WERRIBEE HYDRANT BOOSTER CONNECTION
644,WER,EXT-W701,WERRIBEE HYDRANT BOOSTER PUMP SET
645,RES,L267,STUDENT ACCOMMODATION SITE (123-135 BOUVERIE ST)
646,WER,L410,WERRIBEE GROUND LEASES OF CROWN LAND
647,STH,L880,LAND (GROUND LEASE IAN POTTER SOUTHBANK CENTRE)

In [7]:
# rename the 'Building Code' column to 'No'
mapping_naming = mapping_naming.rename(columns={'Building Code': 'No'})

In [8]:
# create a dictionary from the mapping DataFrame
mapping_dict = dict(zip(mapping_naming['No'], mapping_naming['Building Name']))

In [9]:
# use the map function to replace the building names in the original DataFrame
df['Building name'] = df['No'].map(mapping_dict)

,Building name,No,url,Building name_2
0,ACADEMIC CENTRE - MAIN BUILDING,505,https://use.mazemap.com/?campusid=220&sharepoi...,DOOKIE ACADEMIC CENTRE (MAIN BUILDING)
1,PATRICK RYAN HALL,506,https://use.mazemap.com/?campusid=220&sharepoi...,DOOKIE - PATRICK RYAN HALL
2,SWINBURNE HALL,507,https://use.mazemap.com/?campusid=220&sharepoi...,DOOKIE - SWINBURNE HALL
3,SCIENCE LABORATORY,510,https://use.mazemap.com/?campusid=220&sharepoi...,RESEARCH LABORATORIES
4,C LECTURE THEATRE - 1911,519,https://use.mazemap.com/?campusid=220&sharepoi...,DOOKIE HERITAGE 1911 BUILDING (MUSEUM & TEACHING)
5,HUGH PYE,527,https://use.mazemap.com/?campusid=220&sharepoi...,DOOKIE HUGH PYE BUILDING
6,D LECTURE THEATRE,528,https://use.mazemap.com/?campusid=220&sharepoi...,TEACHING SPACES D
7,E LECTURE THEATRE,529,https://use.mazemap.com/?campusid=220&sharepoi...,TEACHING SPACES E
8,WINERY BUILDING,535,https://use.mazemap.com/?campusid=220&sharepoi...,DOOKIE WINERY BUILDING
9,GILBERT CHANDLER COMMUNITY CENTRE,540,https://use.mazemap.com/?campusid=220&sharepoi...,DOOKIE GILBERT CHANDLER DINING HALL
10,CONFERENCE HOUSE,542,https://use.mazemap.com/?campusid=220&sharepoi...,DOOKIE CONFERENCE CENTRE
11,GAVIN GIBSON LEARNING CENTRE,541,https://use.mazemap.com/?campusid=220&sharepoi...,DOOKIE GAVIN GIBSON LEARNING CENTRE
12,OLD AGRICULTURAL ENGINEERING,545,https://use.mazemap.com/?campusid=220&sharepoi...,DOOKIE ENGAGEMENT CENTRE
13,NEW AGRICULTURAL ENGINEERING,546,https://use.mazemap.com/?campusid=220&sharepoi...,DOOKIE NEW AGRICULTURAL ENGINEERING BUILDING

In [37]:
df.to_excel("./mapping/unimelb_southbank_url.xlsx", index=False)